spring.application.name=demo

spring.datasource.url=jdbc:mysql://localhost:3306/Sample
spring.datasource.username:root
spring.datasource.password:tommy123

driver-class-name: com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

cache.capacity=5